Construção da métrica que quantifica a demanda por trabalhadores do TI

1 - Irei carregar as colunas relevantes ('subsetor_ibge_valor', 'ano', 'faixa_salarial', 'valor_remuneracao_media', 'descricao')

2 - Vamos dividir em 2 dataframes, o 1º que retorne a distribuição de funcionário por subsetor ao longo do ano e 2º que retorne a distribuição de funções ao longo do ano.

3 - Vamos tirar a média salarial de cada distribuição (std e amplitude).

4 - Iremos tirar o desvio padrão das médias salariais ao longo dos anos.

Os setores com maior crescimento do desvio padrão vão representar os setores que mais tem apresentado uma maior demanda ao longo dos anos.

In [3]:
import pandas as pd
import numpy as np
import matplotlib as plt
import seaborn as sns

df_original = pd.read_csv('C:/Users/Matheus Rosetti/Documents/RESIDENCIA/Imersao/data/df_principal2.csv')
df = df_original.copy()

In [4]:
demanda_subsetor = ['subsetor_ibge_valor', 'ano', 'faixa_salarial', 'valor_remuneracao_media']
df_demanda_subsetor = df[demanda_subsetor].copy()

display(df_demanda_subsetor)

,subsetor_ibge_valor,ano,faixa_salarial,valor_remuneracao_media
0,Comércio atacadista,2019,"0,51 a 1,00 salários mínimos",1272.33
1,Comércio atacadista,2019,"0,51 a 1,00 salários mínimos",1272.33
2,Comércio varejista,2019,"0,51 a 1,00 salários mínimos",1344.47
3,Comércio varejista,2019,"0,51 a 1,00 salários mínimos",1344.47
4,"Ind. da borracha, fumo, couros, peles, similar...",2019,"1,51 a 2,00 salários mínimos",2624.93
...,...,...,...,...
2134031,"Com. e administraçao de imóveis, valores mobil...",2022,zero/não declarado,0.00
2134032,"Com. e administraçao de imóveis, valores mobil...",2022,zero/não declarado,0.00
2134033,"Com. e administraçao de imóveis, valores mobil...",2022,zero/não declarado,0.00
2134034,"Com. e administraçao de imóveis, valores mobil...",2022,zero/não declarado,0.00
2134035,"Com. e administraçao de imóveis, valores mobil...",2022,zero/não declarado,0.00

In [5]:
df_demanda_subsetor['cont_freq_subsetor'] = df_demanda_subsetor.groupby('subsetor_ibge_valor')['subsetor_ibge_valor'].transform('count')

display(df_demanda_subsetor)

,subsetor_ibge_valor,ano,faixa_salarial,valor_remuneracao_media,cont_freq_subsetor
0,Comércio atacadista,2019,"0,51 a 1,00 salários mínimos",1272.33,53548
1,Comércio atacadista,2019,"0,51 a 1,00 salários mínimos",1272.33,53548
2,Comércio varejista,2019,"0,51 a 1,00 salários mínimos",1344.47,132492
3,Comércio varejista,2019,"0,51 a 1,00 salários mínimos",1344.47,132492
4,"Ind. da borracha, fumo, couros, peles, similar...",2019,"1,51 a 2,00 salários mínimos",2624.93,10178
...,...,...,...,...,...
2134031,"Com. e administraçao de imóveis, valores mobil...",2022,zero/não declarado,0.00,1246802
2134032,"Com. e administraçao de imóveis, valores mobil...",2022,zero/não declarado,0.00,1246802
2134033,"Com. e administraçao de imóveis, valores mobil...",2022,zero/não declarado,0.00,1246802
2134034,"Com. e administraçao de imóveis, valores mobil...",2022,zero/não declarado,0.00,1246802
2134035,"Com. e administraçao de imóveis, valores mobil...",2022,zero/não declarado,0.00,1246802

In [13]:
zero_values = df_demanda_subsetor[df_demanda_subsetor['valor_remuneracao_media'] == 0]['valor_remuneracao_media'].value_counts()
print(zero_values)

valor_remuneracao_media
0.0    59540
Name: count, dtype: int64

In [14]:
df_demanda_subsetor = df_demanda_subsetor[~df_demanda_subsetor['valor_remuneracao_media'].isin([0])]

In [15]:
df_demanda_subsetor['media_remuneracao_subsetor_ano'] = df_demanda_subsetor.groupby(['subsetor_ibge_valor', 'ano'])['valor_remuneracao_media'].transform('mean')
df_demanda_subsetor['std_remuneracao_subsetor_ano'] = df_demanda_subsetor.groupby(['subsetor_ibge_valor', 'ano'])['valor_remuneracao_media'].transform('std')
df_demanda_subsetor['q1_remuneracao_subsetor_ano'] = df_demanda_subsetor.groupby(['subsetor_ibge_valor', 'ano'])['valor_remuneracao_media'].transform(lambda x: x.quantile(0.25))
df_demanda_subsetor['q3_remuneracao_subsetor_ano'] = df_demanda_subsetor.groupby(['subsetor_ibge_valor', 'ano'])['valor_remuneracao_media'].transform(lambda x: x.quantile(0.75))

display(df_demanda_subsetor)

C:\Users\Matheus Rosetti\AppData\Local\Temp\ipykernel_25736\557672517.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_demanda_subsetor['media_remuneracao_subsetor_ano'] = df_demanda_subsetor.groupby(['subsetor_ibge_valor', 'ano'])['valor_remuneracao_media'].transform('mean')
C:\Users\Matheus Rosetti\AppData\Local\Temp\ipykernel_25736\557672517.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_demanda_subsetor['std_remuneracao_subsetor_ano'] = df_demanda_subsetor.groupby(['subsetor_ibge_valor', 'ano'])['valor_remuneracao_media'].transform('std')
C:\Users\Matheus Rosetti\AppData\Local\Temp\ipykernel_25736\557672517.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_demanda_subsetor['q1_remuneracao_subsetor_ano'] = df_demanda_subsetor.groupby(['subsetor_ibge_valor', 'ano'])['valor_remuneracao_media'].transform(lambda x: x.quantile(0.25))
C:\Users\Matheus Rosetti\AppData\Local\Temp\ipykernel_25736\557672517.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_demanda_subsetor['q3_remuneracao_subsetor_ano'] = df_demanda_subsetor.groupby(['subsetor_ibge_valor', 'ano'])['valor_remuneracao_media'].transform(lambda x: x.quantile(0.75))

,subsetor_ibge_valor,ano,faixa_salarial,valor_remuneracao_media,cont_freq_subsetor,media_remuneracao_subsetor_ano,std_remuneracao_subsetor_ano,q1_remuneracao_subsetor_ano,q3_remuneracao_subsetor_ano
0,Comércio atacadista,2019,"0,51 a 1,00 salários mínimos",1272.33,53548,5907.603093,6313.427089,2183.2175,7254.1850
1,Comércio atacadista,2019,"0,51 a 1,00 salários mínimos",1272.33,53548,5907.603093,6313.427089,2183.2175,7254.1850
2,Comércio varejista,2019,"0,51 a 1,00 salários mínimos",1344.47,132492,4026.416438,3876.408198,1627.6125,4836.0325
3,Comércio varejista,2019,"0,51 a 1,00 salários mínimos",1344.47,132492,4026.416438,3876.408198,1627.6125,4836.0325
4,"Ind. da borracha, fumo, couros, peles, similar...",2019,"1,51 a 2,00 salários mínimos",2624.93,10178,4460.897734,3603.453922,2049.0100,5924.0000
...,...,...,...,...,...,...,...,...,...
2134013,"Com. e administraçao de imóveis, valores mobil...",2022,"0,51 a 1,00 salários mínimos",1462.54,1246802,7266.186770,11404.934250,2481.9925,8690.5300
2134022,Ensino,2022,"1,01 a 1,50 salários mínimos",1764.00,65172,5514.579721,6185.424974,2184.2700,7000.0000
2134023,Ensino,2022,"1,01 a 1,50 salários mínimos",1764.00,65172,5514.579721,6185.424974,2184.2700,7000.0000
2134024,"Com. e administraçao de imóveis, valores mobil...",2022,"4,01 a 5,00 salários mínimos",7278.62,1246802,7266.186770,11404.934250,2481.9925,8690.5300
2134025,"Com. e administraçao de imóveis, valores mobil...",2022,"4,01 a 5,00 salários mínimos",7278.62,1246802,7266.186770,11404.934250,2481.9925,8690.5300