In [7]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [8]:
df_descricao_natureza_juridica = pd.read_excel('df_descricao_por_natureza_juridica.xlsx')

display(df_descricao_natureza_juridica)

,ano,tamanho_estabelecimento_valor,natureza_juridica_valor,descricao,cont_freq_descricao,media_freq_descricao,std_freq_descricao,min_freq_descricao,max_freq_descricao,q1_freq_descricao,mediana_freq_descricao,q3_freq_descricao,faixa_salarial,media_remuneracao,std_remuneracao,min_remuneracao,max_remuneracao,q1_remuneracao,mediana_remuneracao,q3_remuneracao
0,2019-01-01,1000 ou mais,Associação Privada,Administrador De Banco De Dados,10,46.417266,107.562939,2,1034,2,6,26.0,"5,01 a 7,00 salários mínimos",6877.515984,4593.229958,0,39628.786667,3290.025625,6536.668333,9392.807500
1,NaT,NaN,NaN,Administrador De Redes,38,36.656101,75.604195,2,452,2,6,24.0,"4,01 a 5,00 salários mínimos",7063.371150,5648.173679,0,64135.870000,3649.470000,5829.430000,8621.830000
2,NaT,NaN,NaN,Administrador De Sistemas Operacionais,50,47.412463,101.669331,2,644,2,6,30.0,"2,01 a 3,00 salários mínimos",6932.979980,6040.753965,0,61952.860000,2707.628492,5313.730000,9523.901923
3,NaT,NaN,NaN,Administrador Em Segurança Da Informação,8,64.491071,134.654118,2,848,2,8,38.5,"10,01 a 15,00 salários mínimos",7059.620284,3922.437614,0,32593.690000,4626.330603,6750.494375,8812.249509
4,NaT,NaN,NaN,Analista De Desenvolvimento De Sistemas,596,521.037241,1845.953162,2,18830,4,16,153.5,"4,01 a 5,00 salários mínimos",8237.631220,6212.204099,0,80852.450000,4319.398333,6763.379519,10028.227797
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12147,NaT,NaN,NaN,Analista De Suporte Computacional,8,284.758741,905.355767,2,6330,4,12,74.0,"2,01 a 3,00 salários mínimos",6232.198557,6497.207825,0,106152.600000,3130.033214,4588.835343,6751.382080
12148,NaT,NaN,NaN,Desenvolvedor De Sistemas De Tecnologia Da Inf...,10,281.506562,1199.165055,2,18964,4,12,72.0,"0,51 a 1,00 salários mínimos",5876.066041,5927.748435,0,113021.300000,3078.941250,4638.699167,6935.928118
12149,NaT,NaN,NaN,Desenvolvedor Web (Técnico),4,45.062827,89.902083,2,458,2,8,30.0,zero/não declarado,4501.963641,4695.462460,0,49078.330000,2181.433333,3364.336171,5608.554545
12150,NaT,NaN,NaN,Operador De Computador,4,98.113274,286.015010,2,2894,4,10,42.0,zero/não declarado,3526.558228,3199.343173,0,33987.310000,1764.275625,2518.905030,4054.178389
12151,NaT,NaN,NaN,Técnico De Suporte Ao Usuário De Tecnologia Da...,12,181.285484,591.504364,2,5538,4,14,68.0,"1,51 a 2,00 salários mínimos",3661.610304,3410.106267,0,37681.060000,1984.715000,2605.231825,3985.898466

In [9]:
df_descricao_natureza_juridica['ano'] = df_descricao_natureza_juridica['ano'].ffill()
df_descricao_natureza_juridica['tamanho_estabelecimento_valor'] = df_descricao_natureza_juridica['tamanho_estabelecimento_valor'].ffill()
df_descricao_natureza_juridica['natureza_juridica_valor'] = df_descricao_natureza_juridica['natureza_juridica_valor'].ffill()

display(df_descricao_natureza_juridica)

,ano,tamanho_estabelecimento_valor,natureza_juridica_valor,descricao,cont_freq_descricao,media_freq_descricao,std_freq_descricao,min_freq_descricao,max_freq_descricao,q1_freq_descricao,mediana_freq_descricao,q3_freq_descricao,faixa_salarial,media_remuneracao,std_remuneracao,min_remuneracao,max_remuneracao,q1_remuneracao,mediana_remuneracao,q3_remuneracao
0,2019-01-01,1000 ou mais,Associação Privada,Administrador De Banco De Dados,10,46.417266,107.562939,2,1034,2,6,26.0,"5,01 a 7,00 salários mínimos",6877.515984,4593.229958,0,39628.786667,3290.025625,6536.668333,9392.807500
1,2019-01-01,1000 ou mais,Associação Privada,Administrador De Redes,38,36.656101,75.604195,2,452,2,6,24.0,"4,01 a 5,00 salários mínimos",7063.371150,5648.173679,0,64135.870000,3649.470000,5829.430000,8621.830000
2,2019-01-01,1000 ou mais,Associação Privada,Administrador De Sistemas Operacionais,50,47.412463,101.669331,2,644,2,6,30.0,"2,01 a 3,00 salários mínimos",6932.979980,6040.753965,0,61952.860000,2707.628492,5313.730000,9523.901923
3,2019-01-01,1000 ou mais,Associação Privada,Administrador Em Segurança Da Informação,8,64.491071,134.654118,2,848,2,8,38.5,"10,01 a 15,00 salários mínimos",7059.620284,3922.437614,0,32593.690000,4626.330603,6750.494375,8812.249509
4,2019-01-01,1000 ou mais,Associação Privada,Analista De Desenvolvimento De Sistemas,596,521.037241,1845.953162,2,18830,4,16,153.5,"4,01 a 5,00 salários mínimos",8237.631220,6212.204099,0,80852.450000,4319.398333,6763.379519,10028.227797
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12147,2024-01-01,ZERO,Sociedade Unipessoal de Advogados,Analista De Suporte Computacional,8,284.758741,905.355767,2,6330,4,12,74.0,"2,01 a 3,00 salários mínimos",6232.198557,6497.207825,0,106152.600000,3130.033214,4588.835343,6751.382080
12148,2024-01-01,ZERO,Sociedade Unipessoal de Advogados,Desenvolvedor De Sistemas De Tecnologia Da Inf...,10,281.506562,1199.165055,2,18964,4,12,72.0,"0,51 a 1,00 salários mínimos",5876.066041,5927.748435,0,113021.300000,3078.941250,4638.699167,6935.928118
12149,2024-01-01,ZERO,Sociedade Unipessoal de Advogados,Desenvolvedor Web (Técnico),4,45.062827,89.902083,2,458,2,8,30.0,zero/não declarado,4501.963641,4695.462460,0,49078.330000,2181.433333,3364.336171,5608.554545
12150,2024-01-01,ZERO,Sociedade Unipessoal de Advogados,Operador De Computador,4,98.113274,286.015010,2,2894,4,10,42.0,zero/não declarado,3526.558228,3199.343173,0,33987.310000,1764.275625,2518.905030,4054.178389
12151,2024-01-01,ZERO,Sociedade Unipessoal de Advogados,Técnico De Suporte Ao Usuário De Tecnologia Da...,12,181.285484,591.504364,2,5538,4,14,68.0,"1,51 a 2,00 salários mínimos",3661.610304,3410.106267,0,37681.060000,1984.715000,2605.231825,3985.898466

In [10]:
df_descricao_natureza_juridica.to_excel('df_descricao_por_natureza_juridica2.xlsx', index=False)

In [11]:
df_subsetor_uf = pd.read_excel('df_subsetor_por_uf.xlsx')

display(df_subsetor_uf)

,ano,sigla_uf,subsetor_ibge_valor,cont_freq_subsetor,media_valor_remuneracao,media,std,min,max,q1,mediana,q3,media_remuneracao,std_remuneracao,min_remuneracao,max_remuneracao,q1_remuneracao,mediana_remuneracao,q3_remuneracao,faixa_salarial
0,2019.0,AC,Administraçao pública direta e autárquica,28,6291.811429,708.926174,2613.566296,2,19192,88.0,158,452.0,7356.679838,3550.971980,0.000000,19849.114790,4869.605098,6671.445000,9297.725804,"4,01 a 5,00 salários mínimos"
1,NaN,NaN,"Com. e administraçao de imóveis, valores mobil...",66,2884.730606,7556.375758,18413.155409,14,109928,412.0,1358,6900.0,4395.438117,1531.782543,1673.886364,9166.882308,3109.984387,4096.519500,5450.759378,"1,51 a 2,00 salários mínimos"
2,NaN,NaN,Comércio atacadista,2,2692.160000,330.543210,784.619226,2,5148,46.0,95,235.5,4087.572295,1798.614487,1115.770000,9433.943619,2803.475156,3639.141749,4994.945469,"1,51 a 2,00 salários mínimos"
3,NaN,NaN,Comércio varejista,36,1669.919444,817.851852,2094.417146,16,13452,108.0,269,497.0,2815.453111,1189.074437,1244.740000,6867.928807,1934.669604,2508.958551,3401.092318,"1,01 a 1,50 salários mínimos"
4,NaN,NaN,Construçao civil,2,1520.000000,131.275000,295.757549,2,1710,16.0,41,106.0,2620.181024,1019.547674,0.000000,5973.426389,2045.707750,2580.038463,3183.948786,"1,01 a 1,50 salários mínimos"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3404,NaN,NaN,"Instituiçoes de crédito, seguros e capitalizaçao",12,4235.485000,975.542484,3542.760301,2,22830,28.0,84,464.0,6260.494255,3735.795936,1249.916667,34535.529160,3770.460833,5201.205556,8210.185588,"2,01 a 3,00 salários mínimos"
3405,NaN,NaN,"Serv. de alojamento, alimentaçao, reparaçao, m...",22,4227.104545,269.246914,496.389699,2,2736,44.0,93,239.0,3921.514355,1761.168810,933.765333,9121.359625,2532.869896,3532.500833,4984.337535,"2,01 a 3,00 salários mínimos"
3406,NaN,NaN,Serviços industriais de utilidade pública,4,3714.850000,62.815287,86.228663,2,436,12.0,28,74.0,9568.164781,3635.425450,0.000000,21549.694138,7243.500000,9239.295946,11274.409634,"2,01 a 3,00 salários mínimos"
3407,NaN,NaN,"Serviços médicos, odontológicos e veterinários",30,3781.962667,213.654321,454.642339,2,2772,34.0,69,210.0,3580.886712,1433.893180,687.060000,9154.774929,2657.337669,3328.874222,4015.550029,"2,01 a 3,00 salários mínimos"
3408,NaN,NaN,Transportes e comunicaçoes,86,2614.280233,793.717791,1576.568408,2,9214,113.0,250,777.0,3774.558606,2133.065684,1122.398333,15759.728692,2527.556207,3126.170948,3982.209573,"1,51 a 2,00 salários mínimos"

In [12]:
df_subsetor_uf['ano'] = df_subsetor_uf['ano'].ffill()
df_subsetor_uf['sigla_uf'] = df_subsetor_uf['sigla_uf'].ffill()


display(df_subsetor_uf)

,ano,sigla_uf,subsetor_ibge_valor,cont_freq_subsetor,media_valor_remuneracao,media,std,min,max,q1,mediana,q3,media_remuneracao,std_remuneracao,min_remuneracao,max_remuneracao,q1_remuneracao,mediana_remuneracao,q3_remuneracao,faixa_salarial
0,2019.0,AC,Administraçao pública direta e autárquica,28,6291.811429,708.926174,2613.566296,2,19192,88.0,158,452.0,7356.679838,3550.971980,0.000000,19849.114790,4869.605098,6671.445000,9297.725804,"4,01 a 5,00 salários mínimos"
1,2019.0,AC,"Com. e administraçao de imóveis, valores mobil...",66,2884.730606,7556.375758,18413.155409,14,109928,412.0,1358,6900.0,4395.438117,1531.782543,1673.886364,9166.882308,3109.984387,4096.519500,5450.759378,"1,51 a 2,00 salários mínimos"
2,2019.0,AC,Comércio atacadista,2,2692.160000,330.543210,784.619226,2,5148,46.0,95,235.5,4087.572295,1798.614487,1115.770000,9433.943619,2803.475156,3639.141749,4994.945469,"1,51 a 2,00 salários mínimos"
3,2019.0,AC,Comércio varejista,36,1669.919444,817.851852,2094.417146,16,13452,108.0,269,497.0,2815.453111,1189.074437,1244.740000,6867.928807,1934.669604,2508.958551,3401.092318,"1,01 a 1,50 salários mínimos"
4,2019.0,AC,Construçao civil,2,1520.000000,131.275000,295.757549,2,1710,16.0,41,106.0,2620.181024,1019.547674,0.000000,5973.426389,2045.707750,2580.038463,3183.948786,"1,01 a 1,50 salários mínimos"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3404,2024.0,TO,"Instituiçoes de crédito, seguros e capitalizaçao",12,4235.485000,975.542484,3542.760301,2,22830,28.0,84,464.0,6260.494255,3735.795936,1249.916667,34535.529160,3770.460833,5201.205556,8210.185588,"2,01 a 3,00 salários mínimos"
3405,2024.0,TO,"Serv. de alojamento, alimentaçao, reparaçao, m...",22,4227.104545,269.246914,496.389699,2,2736,44.0,93,239.0,3921.514355,1761.168810,933.765333,9121.359625,2532.869896,3532.500833,4984.337535,"2,01 a 3,00 salários mínimos"
3406,2024.0,TO,Serviços industriais de utilidade pública,4,3714.850000,62.815287,86.228663,2,436,12.0,28,74.0,9568.164781,3635.425450,0.000000,21549.694138,7243.500000,9239.295946,11274.409634,"2,01 a 3,00 salários mínimos"
3407,2024.0,TO,"Serviços médicos, odontológicos e veterinários",30,3781.962667,213.654321,454.642339,2,2772,34.0,69,210.0,3580.886712,1433.893180,687.060000,9154.774929,2657.337669,3328.874222,4015.550029,"2,01 a 3,00 salários mínimos"
3408,2024.0,TO,Transportes e comunicaçoes,86,2614.280233,793.717791,1576.568408,2,9214,113.0,250,777.0,3774.558606,2133.065684,1122.398333,15759.728692,2527.556207,3126.170948,3982.209573,"1,51 a 2,00 salários mínimos"

In [13]:
df_subsetor_uf['sigla_uf'] = "BR-" + df_subsetor_uf['sigla_uf']

display(df_subsetor_uf)

,ano,sigla_uf,subsetor_ibge_valor,cont_freq_subsetor,media_valor_remuneracao,media,std,min,max,q1,mediana,q3,media_remuneracao,std_remuneracao,min_remuneracao,max_remuneracao,q1_remuneracao,mediana_remuneracao,q3_remuneracao,faixa_salarial
0,2019.0,BR-AC,Administraçao pública direta e autárquica,28,6291.811429,708.926174,2613.566296,2,19192,88.0,158,452.0,7356.679838,3550.971980,0.000000,19849.114790,4869.605098,6671.445000,9297.725804,"4,01 a 5,00 salários mínimos"
1,2019.0,BR-AC,"Com. e administraçao de imóveis, valores mobil...",66,2884.730606,7556.375758,18413.155409,14,109928,412.0,1358,6900.0,4395.438117,1531.782543,1673.886364,9166.882308,3109.984387,4096.519500,5450.759378,"1,51 a 2,00 salários mínimos"
2,2019.0,BR-AC,Comércio atacadista,2,2692.160000,330.543210,784.619226,2,5148,46.0,95,235.5,4087.572295,1798.614487,1115.770000,9433.943619,2803.475156,3639.141749,4994.945469,"1,51 a 2,00 salários mínimos"
3,2019.0,BR-AC,Comércio varejista,36,1669.919444,817.851852,2094.417146,16,13452,108.0,269,497.0,2815.453111,1189.074437,1244.740000,6867.928807,1934.669604,2508.958551,3401.092318,"1,01 a 1,50 salários mínimos"
4,2019.0,BR-AC,Construçao civil,2,1520.000000,131.275000,295.757549,2,1710,16.0,41,106.0,2620.181024,1019.547674,0.000000,5973.426389,2045.707750,2580.038463,3183.948786,"1,01 a 1,50 salários mínimos"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3404,2024.0,BR-TO,"Instituiçoes de crédito, seguros e capitalizaçao",12,4235.485000,975.542484,3542.760301,2,22830,28.0,84,464.0,6260.494255,3735.795936,1249.916667,34535.529160,3770.460833,5201.205556,8210.185588,"2,01 a 3,00 salários mínimos"
3405,2024.0,BR-TO,"Serv. de alojamento, alimentaçao, reparaçao, m...",22,4227.104545,269.246914,496.389699,2,2736,44.0,93,239.0,3921.514355,1761.168810,933.765333,9121.359625,2532.869896,3532.500833,4984.337535,"2,01 a 3,00 salários mínimos"
3406,2024.0,BR-TO,Serviços industriais de utilidade pública,4,3714.850000,62.815287,86.228663,2,436,12.0,28,74.0,9568.164781,3635.425450,0.000000,21549.694138,7243.500000,9239.295946,11274.409634,"2,01 a 3,00 salários mínimos"
3407,2024.0,BR-TO,"Serviços médicos, odontológicos e veterinários",30,3781.962667,213.654321,454.642339,2,2772,34.0,69,210.0,3580.886712,1433.893180,687.060000,9154.774929,2657.337669,3328.874222,4015.550029,"2,01 a 3,00 salários mínimos"
3408,2024.0,BR-TO,Transportes e comunicaçoes,86,2614.280233,793.717791,1576.568408,2,9214,113.0,250,777.0,3774.558606,2133.065684,1122.398333,15759.728692,2527.556207,3126.170948,3982.209573,"1,51 a 2,00 salários mínimos"

In [14]:
df_subsetor_uf.to_excel('df_subsetor_por_uf2.xlsx', index=False)

In [15]:
df_principal_original = pd.read_csv('C:/Users/Matheus Rosetti/Documents/RESIDENCIA/Imersao/data/df_principal2.csv')

df_principal = df_principal_original.copy()

display(df_principal)

,ano,sigla_uf,cnae_2,sexo,idade,raca_cor,grau_instrucao_apos_2005,tipo_vinculo,tempo_emprego,mes_admissao,...,grau_instrucao_apos_2005_valor,natureza_juridica_valor,nome,descricao,familia,descricao_familia,subgrupo,descricao_subgrupo,subsetor_ibge_valor,faixa_salarial
0,2019,CE,46397,1,27,8,8,10,9.9,NaN,...,SUP. INCOMP,Sociedade Empresária Limitada,Forquilha,Analista De Suporte Computacional,2124,Analistas de tecnologia da informação,212,Profissionais Da Informática,Comércio atacadista,"0,51 a 1,00 salários mínimos"
1,2019,CE,46397,1,27,8,8,10,9.9,NaN,...,SUP. INCOMP,Sociedade Empresária Limitada,Forquilha,Analista De Suporte Computacional,2124,Analistas de tecnologia da informação,212,Profissionais Da Informática,Comércio atacadista,"0,51 a 1,00 salários mínimos"
2,2019,RS,47539,1,19,2,6,10,7.9,5.0,...,MEDIO INCOMP,Sociedade Empresária Limitada,Portão,Técnico De Suporte Ao Usuário De Tecnologia Da...,3172,Técnicos de suporte e monitoração ao usuário d...,317,Técnicos Em Informática,Comércio varejista,"0,51 a 1,00 salários mínimos"
3,2019,RS,47539,1,19,2,6,10,7.9,5.0,...,MEDIO INCOMP,Sociedade Empresária Limitada,Portão,Técnico De Suporte Ao Usuário De Tecnologia Da...,3172,Técnicos de suporte e monitoração ao usuário d...,317,Técnicos Em Informática,Comércio varejista,"0,51 a 1,00 salários mínimos"
4,2019,RS,15106,1,29,2,8,10,7.8,5.0,...,SUP. INCOMP,Sociedade Empresária Limitada,Portão,Analista De Suporte Computacional,2124,Analistas de tecnologia da informação,212,Profissionais Da Informática,"Ind. da borracha, fumo, couros, peles, similar...","1,51 a 2,00 salários mínimos"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2134031,2022,MS,95118,1,38,8,7,10,88.4,NaN,...,MEDIO COMPL,Empresa Individual de Responsabilidade Limitad...,Campo Grande,Técnico De Suporte Ao Usuário De Tecnologia Da...,3172,Técnicos de suporte e monitoração ao usuário d...,317,Técnicos Em Informática,"Com. e administraçao de imóveis, valores mobil...",zero/não declarado
2134032,2022,MS,95118,1,30,2,9,10,65.7,NaN,...,SUP. COMP,Sociedade Empresária Limitada,Campo Grande,Analista De Suporte Computacional,2124,Analistas de tecnologia da informação,212,Profissionais Da Informática,"Com. e administraçao de imóveis, valores mobil...",zero/não declarado
2134033,2022,MS,95118,1,30,2,9,10,65.7,NaN,...,SUP. COMP,Sociedade Empresária Limitada,Campo Grande,Analista De Suporte Computacional,2124,Analistas de tecnologia da informação,212,Profissionais Da Informática,"Com. e administraçao de imóveis, valores mobil...",zero/não declarado
2134034,2022,MS,95118,1,33,8,9,10,45.4,NaN,...,SUP. COMP,Empresa Individual de Responsabilidade Limitad...,Campo Grande,Analista De Desenvolvimento De Sistemas,2124,Analistas de tecnologia da informação,212,Profissionais Da Informática,"Com. e administraçao de imóveis, valores mobil...",zero/não declarado
2134035,2022,MS,95118,1,33,8,9,10,45.4,NaN,...,SUP. COMP,Empresa Individual de Responsabilidade Limitad...,Campo Grande,Analista De Desenvolvimento De Sistemas,2124,Analistas de tecnologia da informação,212,Profissionais Da Informática,"Com. e administraçao de imóveis, valores mobil...",zero/não declarado

In [16]:
df_descricao_por_subsetor_gpy = df_principal.groupby(['ano', 'subsetor_ibge_valor', 'descricao'], dropna=False).agg(
    cont_freq_descricao=('descricao', 'size'),
    media_valor_remuneracao=('valor_remuneracao_media', 'mean')
).reset_index()

display(df_descricao_por_subsetor_gpy)

,ano,subsetor_ibge_valor,descricao,cont_freq_descricao,media_valor_remuneracao
0,2019,Administraçao pública direta e autárquica,Administrador De Banco De Dados,108,2339.081667
1,2019,Administraçao pública direta e autárquica,Administrador De Redes,56,5007.063571
2,2019,Administraçao pública direta e autárquica,Administrador De Sistemas Operacionais,236,3616.646356
3,2019,Administraçao pública direta e autárquica,Administrador Em Segurança Da Informação,30,4534.937333
4,2019,Administraçao pública direta e autárquica,Analista De Desenvolvimento De Sistemas,2322,11207.722196
...,...,...,...,...,...
2522,2024,Transportes e comunicaçoes,Engenheiro De Equipamentos Em Computação,6,5953.173333
2523,2024,Transportes e comunicaçoes,Engenheiros De Sistemas Operacionais Em Comput...,46,14462.820000
2524,2024,Transportes e comunicaçoes,Operador De Computador,1100,2300.681218
2525,2024,Transportes e comunicaçoes,Programador De Máquinas - Ferramenta Com Coman...,12,2128.091667
2526,2024,Transportes e comunicaçoes,Técnico De Suporte Ao Usuário De Tecnologia Da...,4320,2136.364741

In [17]:
col_agruped_subsetor = 'descricao'
valor_freq_coluna = 'media_valor_remuneracao'

df_descricao_por_subsetor_gpy['std'] = df_descricao_por_subsetor_gpy.groupby(col_agruped_subsetor)[valor_freq_coluna].transform('std')
df_descricao_por_subsetor_gpy['min'] = df_descricao_por_subsetor_gpy.groupby(col_agruped_subsetor)[valor_freq_coluna].transform('min')
df_descricao_por_subsetor_gpy['max'] = df_descricao_por_subsetor_gpy.groupby(col_agruped_subsetor)[valor_freq_coluna].transform('max')
df_descricao_por_subsetor_gpy['q1'] = df_descricao_por_subsetor_gpy.groupby(col_agruped_subsetor)[valor_freq_coluna].transform(lambda x: x.quantile(0.25))
df_descricao_por_subsetor_gpy['mediana'] = df_descricao_por_subsetor_gpy.groupby(col_agruped_subsetor)[valor_freq_coluna].transform(lambda x: x.quantile(0.50))
df_descricao_por_subsetor_gpy['q3'] = df_descricao_por_subsetor_gpy.groupby(col_agruped_subsetor)[valor_freq_coluna].transform(lambda x: x.quantile(0.75))

display(df_descricao_por_subsetor_gpy)

,ano,subsetor_ibge_valor,descricao,cont_freq_descricao,media_valor_remuneracao,std,min,max,q1,mediana,q3
0,2019,Administraçao pública direta e autárquica,Administrador De Banco De Dados,108,2339.081667,3206.866809,1196.180000,19484.210000,5705.282500,7675.808333,9668.391429
1,2019,Administraçao pública direta e autárquica,Administrador De Redes,56,5007.063571,2457.910419,1805.910000,17208.373333,5755.952500,6813.484286,8196.053069
2,2019,Administraçao pública direta e autárquica,Administrador De Sistemas Operacionais,236,3616.646356,5231.305582,2320.930000,39798.317500,5729.506990,7690.155966,9980.367702
3,2019,Administraçao pública direta e autárquica,Administrador Em Segurança Da Informação,30,4534.937333,3219.586209,2480.590000,26567.850000,6668.824359,8342.391429,10149.349061
4,2019,Administraçao pública direta e autárquica,Analista De Desenvolvimento De Sistemas,2322,11207.722196,3677.533822,4459.746627,34306.128846,6643.821598,7753.255687,9351.370493
...,...,...,...,...,...,...,...,...,...,...,...
2522,2024,Transportes e comunicaçoes,Engenheiro De Equipamentos Em Computação,6,5953.173333,6846.587985,1644.440000,37826.060000,7839.505000,10449.670000,14717.830000
2523,2024,Transportes e comunicaçoes,Engenheiros De Sistemas Operacionais Em Comput...,46,14462.820000,5127.494264,1461.000000,31878.728835,7828.496923,10300.966970,14614.760000
2524,2024,Transportes e comunicaçoes,Operador De Computador,1100,2300.681218,1433.545389,1130.825000,11398.406920,1989.229853,2268.018667,2971.830525
2525,2024,Transportes e comunicaçoes,Programador De Máquinas - Ferramenta Com Coman...,12,2128.091667,1417.432973,1247.753333,11545.520000,2910.885000,3640.737442,4323.123846
2526,2024,Transportes e comunicaçoes,Técnico De Suporte Ao Usuário De Tecnologia Da...,4320,2136.364741,1045.837810,1719.419117,10411.964286,2320.111665,2688.002533,3183.232554

In [18]:
df_descricao_por_subsetor_gpy['ano'] = df_descricao_por_subsetor_gpy['ano'].ffill()
df_descricao_por_subsetor_gpy['subsetor_ibge_valor'] = df_descricao_por_subsetor_gpy['subsetor_ibge_valor'].ffill()
df_descricao_por_subsetor_gpy['descricao'] = df_descricao_por_subsetor_gpy['descricao'].ffill()

df_descricao_por_subsetor_gpy.to_excel("df_descricao_por_subsetor.xlsx", merge_cells=False)

In [22]:
# Mostrar colunas separadas por DataFrame
print("\n=== Colunas do DataFrame df_descricao_natureza_juridica ===")
for col in sorted(df_descricao_natureza_juridica.columns):
    print(f"- {col}")

print("\n=== Colunas do DataFrame df_subsetor_uf ===")
for col in sorted(df_subsetor_uf.columns):
    print(f"- {col}")

print("\n=== Colunas do DataFrame df_principal ===")
for col in sorted(df_principal.columns):
    print(f"- {col}")

print("\n=== Colunas do DataFrame df_descricao_por_subsetor_gpy ===")
for col in sorted(df_descricao_por_subsetor_gpy.columns):
    print(f"- {col}")

# Mostrar colunas que aparecem em mais de um DataFrame
print("\n=== Colunas que aparecem em múltiplos DataFrames ===")
todos_dfs = {
    'df_descricao_natureza_juridica': set(df_descricao_natureza_juridica.columns),
    'df_subsetor_uf': set(df_subsetor_uf.columns),
    'df_principal': set(df_principal.columns),
    'df_descricao_por_subsetor_gpy': set(df_descricao_por_subsetor_gpy.columns)
}

todas_colunas = set().union(*todos_dfs.values())
for coluna in sorted(todas_colunas):
    dfs_com_coluna = [nome for nome, colunas in todos_dfs.items() if coluna in colunas]
    if len(dfs_com_coluna) > 1:
        print(f"- {coluna} (presente em: {', '.join(dfs_com_coluna)})")

=== Colunas do DataFrame df_descricao_natureza_juridica ===
- ano
- cont_freq_descricao
- descricao
- faixa_salarial
- max_freq_descricao
- max_remuneracao
- media_freq_descricao
- media_remuneracao
- mediana_freq_descricao
- mediana_remuneracao
- min_freq_descricao
- min_remuneracao
- natureza_juridica_valor
- q1_freq_descricao
- q1_remuneracao
- q3_freq_descricao
- q3_remuneracao
- std_freq_descricao
- std_remuneracao
- tamanho_estabelecimento_valor

=== Colunas do DataFrame df_subsetor_uf ===
- ano
- cont_freq_subsetor
- faixa_salarial
- max
- max_remuneracao
- media
- media_remuneracao
- media_valor_remuneracao
- mediana
- mediana_remuneracao
- min
- min_remuneracao
- q1
- q1_remuneracao
- q3
- q3_remuneracao
- sigla_uf
- std
- std_remuneracao
- subsetor_ibge_valor

=== Colunas do DataFrame df_principal ===
- ano
- cnae_2
- descricao
- descricao_familia
- descricao_subgrupo
- faixa_salarial
- familia
- grau_instrucao_apos_2005
- grau_instrucao_apos_2005_valor
- idade
- mes_admissao
- mes_desligamento
- natureza_juridica
- natureza_juridica_valor
- nome
- raca_cor
- raca_cor_valor
- sexo
- sexo_valor
- sigla_uf
- subgrupo
- subsetor_ibge
- subsetor_ibge_valor
- tamanho_estabelecimento
- tamanho_estabelecimento_valor
- tempo_emprego
- tipo_vinculo
- valor_remuneracao_media
- valor_salario_contratual
- vinculo_ativo_3112
- vinculo_ativo_3112_valor

=== Colunas do DataFrame df_descricao_por_subsetor_gpy ===
- ano
- cont_freq_descricao
- descricao
- max
- media_valor_remuneracao
- mediana
- min
- q1
- q3
- std
- subsetor_ibge_valor

=== Colunas que aparecem em múltiplos DataFrames ===
- ano (presente em: df_descricao_natureza_juridica, df_subsetor_uf, df_principal, df_descricao_por_subsetor_gpy)
- cont_freq_descricao (presente em: df_descricao_natureza_juridica, df_descricao_por_subsetor_gpy)
- descricao (presente em: df_descricao_natureza_juridica, df_principal, df_descricao_por_subsetor_gpy)
- faixa_salarial (presente em: df_descricao_natureza_juridica, df_subsetor_uf, df_principal)
- max (presente em: df_subsetor_uf, df_descricao_por_subsetor_gpy)
- max_remuneracao (presente em: df_descricao_natureza_juridica, df_subsetor_uf)
- media_remuneracao (presente em: df_descricao_natureza_juridica, df_subsetor_uf)
- media_valor_remuneracao (presente em: df_subsetor_uf, df_descricao_por_subsetor_gpy)
- mediana (presente em: df_subsetor_uf, df_descricao_por_subsetor_gpy)
- mediana_remuneracao (presente em: df_descricao_natureza_juridica, df_subsetor_uf)
- min (presente em: df_subsetor_uf, df_descricao_por_subsetor_gpy)
- min_remuneracao (presente em: df_descricao_natureza_juridica, df_subsetor_uf)
- natureza_juridica_valor (presente em: df_descricao_natureza_juridica, df_principal)
- q1 (presente em: df_subsetor_uf, df_descricao_por_subsetor_gpy)
- q1_remuneracao (presente em: df_descricao_natureza_juridica, df_subsetor_uf)
- q3 (presente em: df_subsetor_uf, df_descricao_por_subsetor_gpy)
- q3_remuneracao (presente em: df_descricao_natureza_juridica, df_subsetor_uf)
- sigla_uf (presente em: df_subsetor_uf, df_principal)
- std (presente em: df_subsetor_uf, df_descricao_por_subsetor_gpy)
- std_remuneracao (presente em: df_descricao_natureza_juridica, df_subsetor_uf)
- subsetor_ibge_valor (presente em: df_subsetor_uf, df_principal, df_descricao_por_subsetor_gpy)
- tamanho_estabelecimento_valor (presente em: df_descricao_natureza_juridica, df_principal)