Construção da métrica que quantifica a demanda por trabalhadores do TI

1 - Irei carregar as colunas relevantes ('subsetor_ibge_valor', 'ano', 'faixa_salarial', 'valor_remuneracao_media', 'descricao')

2 - Vamos dividir em 2 dataframes, o 1º que retorne a distribuição de funcionário por subsetor ao longo do ano e 2º que retorne a distribuição de funções ao longo do ano.

3 - Vamos tirar a média salarial de cada distribuição (std e amplitude).

4 - Iremos tirar o desvio padrão das médias salariais ao longo dos anos.

Os setores com maior crescimento do desvio padrão vão representar os setores que mais tem apresentado uma maior demanda ao longo dos anos.

In [ ]:
import pandas as pd
import numpy as np
import matplotlib as plt
import seaborn as sns
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:


drive_file_path = '/content/drive/MyDrive/RESIDÊNCIA /Imersão /data/df_principal2.csv'

try:
    df_drive = pd.read_csv(drive_file_path)
    df = df_drive.copy()
    print("Dataset carregado com sucesso do Google Drive!")
    display(df)
except FileNotFoundError:
    print(f"Erro: O arquivo não foi encontrado em {drive_file_path}. Verifique o caminho.")
except Exception as e:
    print(f"Ocorreu um erro ao carregar o dataset: {e}")

Dataset carregado com sucesso do Google Drive!

,ano,sigla_uf,cnae_2,sexo,idade,raca_cor,grau_instrucao_apos_2005,tipo_vinculo,tempo_emprego,mes_admissao,...,grau_instrucao_apos_2005_valor,natureza_juridica_valor,nome,descricao,familia,descricao_familia,subgrupo,descricao_subgrupo,subsetor_ibge_valor,faixa_salarial
0,2019,CE,46397,1,27,8,8,10,9.9,NaN,...,SUP. INCOMP,Sociedade Empresária Limitada,Forquilha,Analista De Suporte Computacional,2124,Analistas de tecnologia da informação,212,Profissionais Da Informática,Comércio atacadista,"0,51 a 1,00 salários mínimos"
1,2019,CE,46397,1,27,8,8,10,9.9,NaN,...,SUP. INCOMP,Sociedade Empresária Limitada,Forquilha,Analista De Suporte Computacional,2124,Analistas de tecnologia da informação,212,Profissionais Da Informática,Comércio atacadista,"0,51 a 1,00 salários mínimos"
2,2019,RS,47539,1,19,2,6,10,7.9,5.0,...,MEDIO INCOMP,Sociedade Empresária Limitada,Portão,Técnico De Suporte Ao Usuário De Tecnologia Da...,3172,Técnicos de suporte e monitoração ao usuário d...,317,Técnicos Em Informática,Comércio varejista,"0,51 a 1,00 salários mínimos"
3,2019,RS,47539,1,19,2,6,10,7.9,5.0,...,MEDIO INCOMP,Sociedade Empresária Limitada,Portão,Técnico De Suporte Ao Usuário De Tecnologia Da...,3172,Técnicos de suporte e monitoração ao usuário d...,317,Técnicos Em Informática,Comércio varejista,"0,51 a 1,00 salários mínimos"
4,2019,RS,15106,1,29,2,8,10,7.8,5.0,...,SUP. INCOMP,Sociedade Empresária Limitada,Portão,Analista De Suporte Computacional,2124,Analistas de tecnologia da informação,212,Profissionais Da Informática,"Ind. da borracha, fumo, couros, peles, similar...","1,51 a 2,00 salários mínimos"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2134031,2022,MS,95118,1,38,8,7,10,88.4,NaN,...,MEDIO COMPL,Empresa Individual de Responsabilidade Limitad...,Campo Grande,Técnico De Suporte Ao Usuário De Tecnologia Da...,3172,Técnicos de suporte e monitoração ao usuário d...,317,Técnicos Em Informática,"Com. e administraçao de imóveis, valores mobil...",zero/não declarado
2134032,2022,MS,95118,1,30,2,9,10,65.7,NaN,...,SUP. COMP,Sociedade Empresária Limitada,Campo Grande,Analista De Suporte Computacional,2124,Analistas de tecnologia da informação,212,Profissionais Da Informática,"Com. e administraçao de imóveis, valores mobil...",zero/não declarado
2134033,2022,MS,95118,1,30,2,9,10,65.7,NaN,...,SUP. COMP,Sociedade Empresária Limitada,Campo Grande,Analista De Suporte Computacional,2124,Analistas de tecnologia da informação,212,Profissionais Da Informática,"Com. e administraçao de imóveis, valores mobil...",zero/não declarado
2134034,2022,MS,95118,1,33,8,9,10,45.4,NaN,...,SUP. COMP,Empresa Individual de Responsabilidade Limitad...,Campo Grande,Analista De Desenvolvimento De Sistemas,2124,Analistas de tecnologia da informação,212,Profissionais Da Informática,"Com. e administraçao de imóveis, valores mobil...",zero/não declarado
2134035,2022,MS,95118,1,33,8,9,10,45.4,NaN,...,SUP. COMP,Empresa Individual de Responsabilidade Limitad...,Campo Grande,Analista De Desenvolvimento De Sistemas,2124,Analistas de tecnologia da informação,212,Profissionais Da Informática,"Com. e administraçao de imóveis, valores mobil...",zero/não declarado

In [ ]:
demanda_subsetor = ['subsetor_ibge_valor', 'ano', 'faixa_salarial', 'valor_remuneracao_media']
df_demanda_subsetor = df[demanda_subsetor].copy()

display(df_demanda_subsetor)

,subsetor_ibge_valor,ano,faixa_salarial,valor_remuneracao_media
0,Comércio atacadista,2019,"0,51 a 1,00 salários mínimos",1272.33
1,Comércio atacadista,2019,"0,51 a 1,00 salários mínimos",1272.33
2,Comércio varejista,2019,"0,51 a 1,00 salários mínimos",1344.47
3,Comércio varejista,2019,"0,51 a 1,00 salários mínimos",1344.47
4,"Ind. da borracha, fumo, couros, peles, similar...",2019,"1,51 a 2,00 salários mínimos",2624.93
...,...,...,...,...
2134031,"Com. e administraçao de imóveis, valores mobil...",2022,zero/não declarado,0.00
2134032,"Com. e administraçao de imóveis, valores mobil...",2022,zero/não declarado,0.00
2134033,"Com. e administraçao de imóveis, valores mobil...",2022,zero/não declarado,0.00
2134034,"Com. e administraçao de imóveis, valores mobil...",2022,zero/não declarado,0.00
2134035,"Com. e administraçao de imóveis, valores mobil...",2022,zero/não declarado,0.00

In [ ]:
df_demanda_subsetor = df_demanda_subsetor[~df_demanda_subsetor['valor_remuneracao_media'].isin([0])]

In [ ]:
zero_values = df_demanda_subsetor[df_demanda_subsetor['valor_remuneracao_media'] == 0]['valor_remuneracao_media'].value_counts()
print(zero_values)

Series([], Name: count, dtype: int64)

In [ ]:
df_medianas_anuais = df_demanda_subsetor.groupby(['subsetor_ibge_valor', 'ano'])['valor_remuneracao_media'].median().reset_index()
display(df_medianas_anuais)

                           subsetor_ibge_valor   ano  valor_remuneracao_media
0    Administraçao pública direta e autárquica  2019                  2882.83
1    Administraçao pública direta e autárquica  2020                  3769.27
2    Administraçao pública direta e autárquica  2021                  8544.98
3    Administraçao pública direta e autárquica  2022                  4907.66
4    Administraçao pública direta e autárquica  2023                  9490.82
..                                         ...   ...                      ...
146                 Transportes e comunicaçoes  2020                  3368.84
147                 Transportes e comunicaçoes  2021                  3611.27
148                 Transportes e comunicaçoes  2022                  3855.82
149                 Transportes e comunicaçoes  2023                  3934.86
150                 Transportes e comunicaçoes  2024                  4041.39

[151 rows x 3 columns]

In [ ]:
# --- 3. Preparar dados para o CAGR (Início e Fim) ---
# Precisamos do valor inicial (2023) e final (2024) para cada subsetor
ano_inicial = 2022
ano_final = 2024
n_anos = ano_final - ano_inicial # (2024 - 2023 = 1)

# Filtra apenas os anos que nos interessam
df_medianas_inicio = df_medianas_anuais[df_medianas_anuais['ano'] == ano_inicial]
df_medianas_fim = df_medianas_anuais[df_medianas_anuais['ano'] == ano_final]

In [ ]:
df_cagr = pd.merge(df_medianas_inicio, df_medianas_fim, on='subsetor_ibge_valor', suffixes=('_inicio', '_fim'))

df_cagr = df_cagr.rename(columns={
    'valor_remuneracao_media_inicio': f'mediana_{ano_inicial}',
    'valor_remuneracao_media_fim': f'mediana_{ano_final}'
})

df_cagr = df_cagr.drop(columns=['ano_inicio', 'ano_fim'])

In [ ]:
# --- 4. Calcular o CAGR (Compound Annual Growth Rate) ---
# Fórmula: ((Valor Final / Valor Inicial) ^ (1 / N_Anos)) - 1

# Garante que o valor inicial não é zero para evitar divisão por zero
df_cagr = df_cagr[df_cagr[f'mediana_{ano_inicial}'] > 0]

df_cagr['cagr_mediana_salarial'] = (
    (df_cagr[f'mediana_{ano_final}'] / df_cagr[f'mediana_{ano_inicial}']) ** (1 / n_anos)
) - 1

# --- 5. Exibir Resultado Final ---
# Ordena do maior CAGR (maior demanda) para o menor
df_resultado_cagr = df_cagr.sort_values(by='cagr_mediana_salarial', ascending=False)

print("\n--- (Resultado) Crescimento Percentual por Subsetor (2022-2024) ---")
display(df_resultado_cagr)

print("\n(Para 1 ano, CAGR = Crescimento Percentual Simples)")

--- (Resultado) Crescimento Percentual por Subsetor (2022-2024) ---

,subsetor_ibge_valor,mediana_2022,mediana_2024,cagr_mediana_salarial
0,Administraçao pública direta e autárquica,4907.660,8707.200,0.331993
2,"Com. e administraçao de imóveis, valores mobil...",4629.330,5215.575,0.061432
5,Construçao civil,2699.300,3020.510,0.057827
1,"Agricultura, silvicultura, criaçao de animais,...",4016.150,4482.920,0.056515
12,"Indústria de produtos alimentícios, bebidas e ...",5145.650,5698.325,0.052334
20,"Instituiçoes de crédito, seguros e capitalizaçao",9552.560,10532.645,0.050047
14,Indústria do material de transporte,7362.660,8114.555,0.049820
15,Indústria do material elétrico e de comunicaçoes,5110.595,5617.555,0.048426
22,Serviços industriais de utilidade pública,9559.415,10341.760,0.040116
23,"Serviços médicos, odontológicos e veterinários",3807.360,4087.035,0.036077
11,Indústria de calçados,3279.570,3507.780,0.034208
18,Indústria metalúrgica,4579.750,4897.825,0.034143
19,Indústria têxtil do vestuário e artefatos de t...,3271.685,3455.050,0.027641
17,Indústria mecânica,4675.980,4904.470,0.024141
24,Transportes e comunicaçoes,3855.820,4041.390,0.023781
3,Comércio atacadista,4325.475,4528.415,0.023190
13,Indústria de produtos minerais nao metálicos,4709.915,4871.205,0.016978
10,Indústria da madeira e do mobiliário,4194.330,4293.040,0.011699
16,"Indústria do papel, papelao, editorial e gráfica",4604.165,4686.420,0.008893
8,"Ind. da borracha, fumo, couros, peles, similar...",4029.500,4075.190,0.005653
9,"Ind. química de produtos farmacêuticos, veteri...",6424.295,6260.630,-0.012820
4,Comércio varejista,3188.720,3090.825,-0.015470
21,"Serv. de alojamento, alimentaçao, reparaçao, m...",4414.770,4160.000,-0.029283
7,Extrativa mineral,12699.560,11019.460,-0.068494
6,Ensino,3954.760,3405.665,-0.072015

(Para 1 ano, CAGR = Crescimento Percentual Simples)

In [ ]:
demanda_descricao = ['descricao', 'ano', 'faixa_salarial', 'valor_remuneracao_media']
df_demanda_descricao = df[demanda_descricao].copy()

display(df_demanda_descricao)

,descricao,ano,faixa_salarial,valor_remuneracao_media
0,Analista De Suporte Computacional,2019,"0,51 a 1,00 salários mínimos",1272.33
1,Analista De Suporte Computacional,2019,"0,51 a 1,00 salários mínimos",1272.33
2,Técnico De Suporte Ao Usuário De Tecnologia Da...,2019,"0,51 a 1,00 salários mínimos",1344.47
3,Técnico De Suporte Ao Usuário De Tecnologia Da...,2019,"0,51 a 1,00 salários mínimos",1344.47
4,Analista De Suporte Computacional,2019,"1,51 a 2,00 salários mínimos",2624.93
...,...,...,...,...
2134031,Técnico De Suporte Ao Usuário De Tecnologia Da...,2022,zero/não declarado,0.00
2134032,Analista De Suporte Computacional,2022,zero/não declarado,0.00
2134033,Analista De Suporte Computacional,2022,zero/não declarado,0.00
2134034,Analista De Desenvolvimento De Sistemas,2022,zero/não declarado,0.00
2134035,Analista De Desenvolvimento De Sistemas,2022,zero/não declarado,0.00

In [ ]:
df_demanda_descricao = df_demanda_descricao.dropna(subset=['descricao']).copy()
df_demanda_descricao = df_demanda_descricao[~df_demanda_descricao['valor_remuneracao_media'].isin([0])]

In [ ]:
zero_values = df_demanda_descricao[df_demanda_descricao['valor_remuneracao_media'] == 0]['valor_remuneracao_media'].value_counts()
print(zero_values)

Series([], Name: count, dtype: int64)

In [ ]:
df_medianas_anuais = df_demanda_descricao.groupby(['descricao', 'ano'])['valor_remuneracao_media'].median().reset_index()
display(df_medianas_anuais)

,descricao,ano,valor_remuneracao_media
0,Administrador De Banco De Dados,2019,6513.890
1,Administrador De Banco De Dados,2020,6257.910
2,Administrador De Banco De Dados,2021,6845.830
3,Administrador De Banco De Dados,2022,8105.070
4,Administrador De Banco De Dados,2023,8878.385
...,...,...,...
107,Técnico De Suporte Ao Usuário De Tecnologia Da...,2020,1791.325
108,Técnico De Suporte Ao Usuário De Tecnologia Da...,2021,1870.100
109,Técnico De Suporte Ao Usuário De Tecnologia Da...,2022,2073.300
110,Técnico De Suporte Ao Usuário De Tecnologia Da...,2023,2203.790
111,Técnico De Suporte Ao Usuário De Tecnologia Da...,2024,2281.065

In [ ]:
# --- 3. Preparar dados para o CAGR (Início e Fim) ---
# Precisamos do valor inicial (2023) e final (2024) para cada subsetor
ano_inicial = 2022
ano_final = 2024
n_anos = ano_final - ano_inicial # (2024 - 2023 = 1)

# Filtra apenas os anos que nos interessam
df_medianas_inicio = df_medianas_anuais[df_medianas_anuais['ano'] == ano_inicial]
df_medianas_fim = df_medianas_anuais[df_medianas_anuais['ano'] == ano_final]

In [ ]:
df_cagr_descricao = pd.merge(df_medianas_inicio, df_medianas_fim, on='descricao', suffixes=('_inicio', '_fim'))

df_cagr_descricao = df_cagr_descricao.rename(columns={
    'valor_remuneracao_media_inicio': f'mediana_{ano_inicial}',
    'valor_remuneracao_media_fim': f'mediana_{ano_final}'
})

df_cagr_descricao = df_cagr_descricao.drop(columns=['ano_inicio', 'ano_fim'])

In [ ]:
# --- 4. Calcular o CAGR (Compound Annual Growth Rate) ---
# Fórmula: ((Valor Final / Valor Inicial) ^ (1 / N_Anos)) - 1

# Garante que o valor inicial não é zero para evitar divisão por zero
df_cagr_descricao = df_cagr_descricao[df_cagr_descricao[f'mediana_{ano_inicial}'] > 0]

df_cagr_descricao['cagr_mediana_salarial'] = (
    (df_cagr_descricao[f'mediana_{ano_final}'] / df_cagr_descricao[f'mediana_{ano_inicial}']) ** (1 / n_anos)
) - 1

# --- 5. Exibir Resultado Final ---
# Ordena do maior CAGR (maior demanda) para o menor
df_resultado_cagr_descricao = df_cagr_descricao.sort_values(by='cagr_mediana_salarial', ascending=False)

print("\n--- (Resultado) Crescimento Percentual por Subsetor (2022-2024) ---")
display(df_resultado_cagr_descricao)

print("\n(Para 1 ano, CAGR = Crescimento Percentual Simples)")

--- (Resultado) Crescimento Percentual por Subsetor (2022-2024) ---

,descricao,mediana_2022,mediana_2024,cagr_mediana_salarial
14,Engenheiro De Equipamentos Em Computação,10106.835,14471.610,0.196605
12,Desenvolvedor Web (Técnico),2912.915,3597.740,0.111350
9,Arquiteto De Soluções De Tecnologia Da Informação,12313.630,14500.000,0.085153
6,Analista De Sistemas De Automação,4919.655,5748.955,0.081004
16,Operador De Computador,1813.185,2066.860,0.067664
2,Administrador De Sistemas Operacionais,6826.690,7748.855,0.065402
8,Analista De Testes De Tecnologia Da Informação,4998.925,5611.200,0.059472
17,Programador De Máquinas - Ferramenta Com Coman...,4038.170,4527.840,0.058896
13,Engenheiro De Aplicativos Em Computação,11136.900,12458.330,0.057664
3,Administrador Em Segurança Da Informação,6922.220,7729.500,0.056703
15,Engenheiros De Sistemas Operacionais Em Comput...,11997.135,13234.965,0.050322
18,Técnico De Suporte Ao Usuário De Tecnologia Da...,2073.300,2281.065,0.048909
5,Analista De Redes E De Comunicação De Dados,4500.000,4947.030,0.048494
4,Analista De Desenvolvimento De Sistemas,7432.200,8160.045,0.047822
7,Analista De Suporte Computacional,3329.290,3531.740,0.029956
10,Desenvolvedor De Multimídia,3608.080,3817.360,0.028593
11,Desenvolvedor De Sistemas De Tecnologia Da Inf...,4583.120,4750.000,0.018043
0,Administrador De Banco De Dados,8105.070,7885.570,-0.013634
1,Administrador De Redes,5401.255,5231.780,-0.015814

(Para 1 ano, CAGR = Crescimento Percentual Simples)

In [ ]:
df_descricao_subsetor_original = pd.read_excel('/content/drive/MyDrive/RESIDÊNCIA /Imersão /df_descricao_por_subsetor-LOOKER.xlsx')

df_descricao_subsetor = df_descricao_subsetor_original.copy()

display(df_descricao_subsetor)

,ano,ano_format,subsetor_ibge_valor,descricao,cont_freq_descricao,media_valor_remuneracao,std_remuneracao,min_remuneracao,max_remuneracao,q1_remuneracao,mediana_remuneracao,q3_remuneracao
0,2019,2019-01-01,Administraçao pública direta e autárquica,Administrador De Banco De Dados,108,2339.081667,3206.866809,1196.180000,19484.210000,5705.282500,7675.808333,9668.391429
1,2019,2019-01-01,Administraçao pública direta e autárquica,Administrador De Redes,56,5007.063571,2457.910419,1805.910000,17208.373333,5755.952500,6813.484286,8196.053069
2,2019,2019-01-01,Administraçao pública direta e autárquica,Administrador De Sistemas Operacionais,236,3616.646356,5231.305582,2320.930000,39798.317500,5729.506990,7690.155966,9980.367702
3,2019,2019-01-01,Administraçao pública direta e autárquica,Administrador Em Segurança Da Informação,30,4534.937333,3219.586209,2480.590000,26567.850000,6668.824359,8342.391429,10149.349061
4,2019,2019-01-01,Administraçao pública direta e autárquica,Analista De Desenvolvimento De Sistemas,2322,11207.722196,3677.533822,4459.746627,34306.128846,6643.821598,7753.255687,9351.370493
...,...,...,...,...,...,...,...,...,...,...,...,...
2522,2024,2024-01-01,Transportes e comunicaçoes,Engenheiro De Equipamentos Em Computação,6,5953.173333,6846.587985,1644.440000,37826.060000,7839.505000,10449.670000,14717.830000
2523,2024,2024-01-01,Transportes e comunicaçoes,Engenheiros De Sistemas Operacionais Em Comput...,46,14462.820000,5127.494264,1461.000000,31878.728835,7828.496923,10300.966970,14614.760000
2524,2024,2024-01-01,Transportes e comunicaçoes,Operador De Computador,1100,2300.681218,1433.545389,1130.825000,11398.406920,1989.229853,2268.018667,2971.830525
2525,2024,2024-01-01,Transportes e comunicaçoes,Programador De Máquinas - Ferramenta Com Coman...,12,2128.091667,1417.432973,1247.753333,11545.520000,2910.885000,3640.737442,4323.123846
2526,2024,2024-01-01,Transportes e comunicaçoes,Técnico De Suporte Ao Usuário De Tecnologia Da...,4320,2136.364741,1045.837810,1719.419117,10411.964286,2320.111665,2688.002533,3183.232554

from matplotlib import pyplot as plt
_df_0['index'].plot(kind='hist', bins=20, title='index')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_1['ano'].plot(kind='hist', bins=20, title='ano')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_2['cont_freq_descricao'].plot(kind='hist', bins=20, title='cont_freq_descricao')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_3['media_valor_remuneracao'].plot(kind='hist', bins=20, title='media_valor_remuneracao')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_4.plot(kind='scatter', x='index', y='ano', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_5.plot(kind='scatter', x='ano', y='cont_freq_descricao', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_6.plot(kind='scatter', x='cont_freq_descricao', y='media_valor_remuneracao', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_7.plot(kind='scatter', x='media_valor_remuneracao', y='std_remuneracao', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  palette = list(sns.palettes.mpl_palette('Dark2'))
  xs = series['ano_format']
  ys = series['cont_freq_descricao']

  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = _df_8.sort_values('ano_format', ascending=True)
_plot_series(df_sorted, '')
sns.despine(fig=fig, ax=ax)
plt.xlabel('ano_format')
_ = plt.ylabel('cont_freq_descricao')

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  palette = list(sns.palettes.mpl_palette('Dark2'))
  xs = series['ano_format']
  ys = series['media_valor_remuneracao']

  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = _df_9.sort_values('ano_format', ascending=True)
_plot_series(df_sorted, '')
sns.despine(fig=fig, ax=ax)
plt.xlabel('ano_format')
_ = plt.ylabel('media_valor_remuneracao')

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  palette = list(sns.palettes.mpl_palette('Dark2'))
  xs = series['ano_format']
  ys = series['std_remuneracao']

  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = _df_10.sort_values('ano_format', ascending=True)
_plot_series(df_sorted, '')
sns.despine(fig=fig, ax=ax)
plt.xlabel('ano_format')
_ = plt.ylabel('std_remuneracao')

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  palette = list(sns.palettes.mpl_palette('Dark2'))
  xs = series['ano_format']
  ys = series['min_remuneracao']

  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = _df_11.sort_values('ano_format', ascending=True)
_plot_series(df_sorted, '')
sns.despine(fig=fig, ax=ax)
plt.xlabel('ano_format')
_ = plt.ylabel('min_remuneracao')

from matplotlib import pyplot as plt
_df_12['index'].plot(kind='line', figsize=(8, 4), title='index')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
_df_13['ano'].plot(kind='line', figsize=(8, 4), title='ano')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
_df_14['cont_freq_descricao'].plot(kind='line', figsize=(8, 4), title='cont_freq_descricao')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
_df_15['media_valor_remuneracao'].plot(kind='line', figsize=(8, 4), title='media_valor_remuneracao')
plt.gca().spines[['top', 'right']].set_visible(False)

In [ ]:
df_resultado_cagr = df_resultado_cagr.rename(columns={
    'mediana_2022': 'subsetor_mediana_2022',
    'mediana_2024': 'subsetor_mediana_2024',
    'cagr_mediana_salarial': 'subsetor_cagr_mediana_salarial'
})

df_resultado_cagr_descricao = df_resultado_cagr_descricao.rename(columns={
    'mediana_2022': 'descricao_mediana_2022',
    'mediana_2024': 'descricao_mediana_2024',
    'cagr_mediana_salarial': 'descricao_cagr_mediana_salarial'
})

display(df_resultado_cagr)
display(df_resultado_cagr_descricao)

,subsetor_ibge_valor,subsetor_mediana_2022,subsetor_mediana_2024,subsetor_cagr_mediana_salarial
0,Administraçao pública direta e autárquica,4907.660,8707.200,0.331993
2,"Com. e administraçao de imóveis, valores mobil...",4629.330,5215.575,0.061432
5,Construçao civil,2699.300,3020.510,0.057827
1,"Agricultura, silvicultura, criaçao de animais,...",4016.150,4482.920,0.056515
12,"Indústria de produtos alimentícios, bebidas e ...",5145.650,5698.325,0.052334
20,"Instituiçoes de crédito, seguros e capitalizaçao",9552.560,10532.645,0.050047
14,Indústria do material de transporte,7362.660,8114.555,0.049820
15,Indústria do material elétrico e de comunicaçoes,5110.595,5617.555,0.048426
22,Serviços industriais de utilidade pública,9559.415,10341.760,0.040116
23,"Serviços médicos, odontológicos e veterinários",3807.360,4087.035,0.036077
11,Indústria de calçados,3279.570,3507.780,0.034208
18,Indústria metalúrgica,4579.750,4897.825,0.034143
19,Indústria têxtil do vestuário e artefatos de t...,3271.685,3455.050,0.027641
17,Indústria mecânica,4675.980,4904.470,0.024141
24,Transportes e comunicaçoes,3855.820,4041.390,0.023781
3,Comércio atacadista,4325.475,4528.415,0.023190
13,Indústria de produtos minerais nao metálicos,4709.915,4871.205,0.016978
10,Indústria da madeira e do mobiliário,4194.330,4293.040,0.011699
16,"Indústria do papel, papelao, editorial e gráfica",4604.165,4686.420,0.008893
8,"Ind. da borracha, fumo, couros, peles, similar...",4029.500,4075.190,0.005653
9,"Ind. química de produtos farmacêuticos, veteri...",6424.295,6260.630,-0.012820
4,Comércio varejista,3188.720,3090.825,-0.015470
21,"Serv. de alojamento, alimentaçao, reparaçao, m...",4414.770,4160.000,-0.029283
7,Extrativa mineral,12699.560,11019.460,-0.068494
6,Ensino,3954.760,3405.665,-0.072015

,descricao,descricao_mediana_2022,descricao_mediana_2024,descricao_cagr_mediana_salarial
14,Engenheiro De Equipamentos Em Computação,10106.835,14471.610,0.196605
12,Desenvolvedor Web (Técnico),2912.915,3597.740,0.111350
9,Arquiteto De Soluções De Tecnologia Da Informação,12313.630,14500.000,0.085153
6,Analista De Sistemas De Automação,4919.655,5748.955,0.081004
16,Operador De Computador,1813.185,2066.860,0.067664
2,Administrador De Sistemas Operacionais,6826.690,7748.855,0.065402
8,Analista De Testes De Tecnologia Da Informação,4998.925,5611.200,0.059472
17,Programador De Máquinas - Ferramenta Com Coman...,4038.170,4527.840,0.058896
13,Engenheiro De Aplicativos Em Computação,11136.900,12458.330,0.057664
3,Administrador Em Segurança Da Informação,6922.220,7729.500,0.056703
15,Engenheiros De Sistemas Operacionais Em Comput...,11997.135,13234.965,0.050322
18,Técnico De Suporte Ao Usuário De Tecnologia Da...,2073.300,2281.065,0.048909
5,Analista De Redes E De Comunicação De Dados,4500.000,4947.030,0.048494
4,Analista De Desenvolvimento De Sistemas,7432.200,8160.045,0.047822
7,Analista De Suporte Computacional,3329.290,3531.740,0.029956
10,Desenvolvedor De Multimídia,3608.080,3817.360,0.028593
11,Desenvolvedor De Sistemas De Tecnologia Da Inf...,4583.120,4750.000,0.018043
0,Administrador De Banco De Dados,8105.070,7885.570,-0.013634
1,Administrador De Redes,5401.255,5231.780,-0.015814

In [ ]:
# fazendo left join com o valor natureza juridica
columns_subsetor_carg = df_resultado_cagr[['subsetor_ibge_valor', 'subsetor_mediana_2022', 'subsetor_mediana_2024', 'subsetor_cagr_mediana_salarial']]

df_descricao_subsetor = pd.merge(
        df_descricao_subsetor,
        columns_subsetor_carg,
        left_on= 'subsetor_ibge_valor',
        right_on= 'subsetor_ibge_valor',
        how='left'
    )


print("join subsetor realizado com sucesso")

columns_descricao_carg = df_resultado_cagr_descricao[['descricao', 'descricao_mediana_2022', 'descricao_mediana_2024', 'descricao_cagr_mediana_salarial']]

df_descricao_subsetor = pd.merge(
        df_descricao_subsetor,
        columns_descricao_carg,
        left_on= 'descricao',
        right_on= 'descricao',
        how='left'
    )


print("join descricao realizado com sucesso")

display(df_descricao_subsetor)

join subsetor realizado com sucesso
join descricao realizado com sucesso

,ano,ano_format,subsetor_ibge_valor,descricao,cont_freq_descricao,media_valor_remuneracao,std_remuneracao,min_remuneracao,max_remuneracao,q1_remuneracao,mediana_remuneracao,q3_remuneracao,subsetor_mediana_2022,subsetor_mediana_2024,subsetor_cagr_mediana_salarial,descricao_mediana_2022,descricao_mediana_2024,descricao_cagr_mediana_salarial
0,2019,2019-01-01,Administraçao pública direta e autárquica,Administrador De Banco De Dados,108,2339.081667,3206.866809,1196.180000,19484.210000,5705.282500,7675.808333,9668.391429,4907.66,8707.20,0.331993,8105.070,7885.570,-0.013634
1,2019,2019-01-01,Administraçao pública direta e autárquica,Administrador De Redes,56,5007.063571,2457.910419,1805.910000,17208.373333,5755.952500,6813.484286,8196.053069,4907.66,8707.20,0.331993,5401.255,5231.780,-0.015814
2,2019,2019-01-01,Administraçao pública direta e autárquica,Administrador De Sistemas Operacionais,236,3616.646356,5231.305582,2320.930000,39798.317500,5729.506990,7690.155966,9980.367702,4907.66,8707.20,0.331993,6826.690,7748.855,0.065402
3,2019,2019-01-01,Administraçao pública direta e autárquica,Administrador Em Segurança Da Informação,30,4534.937333,3219.586209,2480.590000,26567.850000,6668.824359,8342.391429,10149.349061,4907.66,8707.20,0.331993,6922.220,7729.500,0.056703
4,2019,2019-01-01,Administraçao pública direta e autárquica,Analista De Desenvolvimento De Sistemas,2322,11207.722196,3677.533822,4459.746627,34306.128846,6643.821598,7753.255687,9351.370493,4907.66,8707.20,0.331993,7432.200,8160.045,0.047822
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2522,2024,2024-01-01,Transportes e comunicaçoes,Engenheiro De Equipamentos Em Computação,6,5953.173333,6846.587985,1644.440000,37826.060000,7839.505000,10449.670000,14717.830000,3855.82,4041.39,0.023781,10106.835,14471.610,0.196605
2523,2024,2024-01-01,Transportes e comunicaçoes,Engenheiros De Sistemas Operacionais Em Comput...,46,14462.820000,5127.494264,1461.000000,31878.728835,7828.496923,10300.966970,14614.760000,3855.82,4041.39,0.023781,11997.135,13234.965,0.050322
2524,2024,2024-01-01,Transportes e comunicaçoes,Operador De Computador,1100,2300.681218,1433.545389,1130.825000,11398.406920,1989.229853,2268.018667,2971.830525,3855.82,4041.39,0.023781,1813.185,2066.860,0.067664
2525,2024,2024-01-01,Transportes e comunicaçoes,Programador De Máquinas - Ferramenta Com Coman...,12,2128.091667,1417.432973,1247.753333,11545.520000,2910.885000,3640.737442,4323.123846,3855.82,4041.39,0.023781,4038.170,4527.840,0.058896
2526,2024,2024-01-01,Transportes e comunicaçoes,Técnico De Suporte Ao Usuário De Tecnologia Da...,4320,2136.364741,1045.837810,1719.419117,10411.964286,2320.111665,2688.002533,3183.232554,3855.82,4041.39,0.023781,2073.300,2281.065,0.048909

In [49]:
from google.colab import files

file_descrica_subsetor_cagr = 'df_demanda_vagas_ti.xlsx'


df_descricao_subsetor.to_excel(file_descrica_subsetor_cagr, merge_cells=False, index=False)

print(f"Os arquivos '{file_descrica_subsetor_cagr}' foram criados e estão prontos para download.")

files.download(file_descrica_subsetor_cagr)

Os arquivos 'df_demanda_vagas_ti.xlsx' foram criados e estão prontos para download.

In [ ]:
df_principal_original = pd.read_csv('/content/drive/MyDrive/RESIDÊNCIA /Imersão /data/df_principal2.csv')

df_principal = df_principal_original.copy()

display(df_principal)

,ano,sigla_uf,cnae_2,sexo,idade,raca_cor,grau_instrucao_apos_2005,tipo_vinculo,tempo_emprego,mes_admissao,...,grau_instrucao_apos_2005_valor,natureza_juridica_valor,nome,descricao,familia,descricao_familia,subgrupo,descricao_subgrupo,subsetor_ibge_valor,faixa_salarial
0,2019,CE,46397,1,27,8,8,10,9.9,NaN,...,SUP. INCOMP,Sociedade Empresária Limitada,Forquilha,Analista De Suporte Computacional,2124,Analistas de tecnologia da informação,212,Profissionais Da Informática,Comércio atacadista,"0,51 a 1,00 salários mínimos"
1,2019,CE,46397,1,27,8,8,10,9.9,NaN,...,SUP. INCOMP,Sociedade Empresária Limitada,Forquilha,Analista De Suporte Computacional,2124,Analistas de tecnologia da informação,212,Profissionais Da Informática,Comércio atacadista,"0,51 a 1,00 salários mínimos"
2,2019,RS,47539,1,19,2,6,10,7.9,5.0,...,MEDIO INCOMP,Sociedade Empresária Limitada,Portão,Técnico De Suporte Ao Usuário De Tecnologia Da...,3172,Técnicos de suporte e monitoração ao usuário d...,317,Técnicos Em Informática,Comércio varejista,"0,51 a 1,00 salários mínimos"
3,2019,RS,47539,1,19,2,6,10,7.9,5.0,...,MEDIO INCOMP,Sociedade Empresária Limitada,Portão,Técnico De Suporte Ao Usuário De Tecnologia Da...,3172,Técnicos de suporte e monitoração ao usuário d...,317,Técnicos Em Informática,Comércio varejista,"0,51 a 1,00 salários mínimos"
4,2019,RS,15106,1,29,2,8,10,7.8,5.0,...,SUP. INCOMP,Sociedade Empresária Limitada,Portão,Analista De Suporte Computacional,2124,Analistas de tecnologia da informação,212,Profissionais Da Informática,"Ind. da borracha, fumo, couros, peles, similar...","1,51 a 2,00 salários mínimos"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2134031,2022,MS,95118,1,38,8,7,10,88.4,NaN,...,MEDIO COMPL,Empresa Individual de Responsabilidade Limitad...,Campo Grande,Técnico De Suporte Ao Usuário De Tecnologia Da...,3172,Técnicos de suporte e monitoração ao usuário d...,317,Técnicos Em Informática,"Com. e administraçao de imóveis, valores mobil...",zero/não declarado
2134032,2022,MS,95118,1,30,2,9,10,65.7,NaN,...,SUP. COMP,Sociedade Empresária Limitada,Campo Grande,Analista De Suporte Computacional,2124,Analistas de tecnologia da informação,212,Profissionais Da Informática,"Com. e administraçao de imóveis, valores mobil...",zero/não declarado
2134033,2022,MS,95118,1,30,2,9,10,65.7,NaN,...,SUP. COMP,Sociedade Empresária Limitada,Campo Grande,Analista De Suporte Computacional,2124,Analistas de tecnologia da informação,212,Profissionais Da Informática,"Com. e administraçao de imóveis, valores mobil...",zero/não declarado
2134034,2022,MS,95118,1,33,8,9,10,45.4,NaN,...,SUP. COMP,Empresa Individual de Responsabilidade Limitad...,Campo Grande,Analista De Desenvolvimento De Sistemas,2124,Analistas de tecnologia da informação,212,Profissionais Da Informática,"Com. e administraçao de imóveis, valores mobil...",zero/não declarado
2134035,2022,MS,95118,1,33,8,9,10,45.4,NaN,...,SUP. COMP,Empresa Individual de Responsabilidade Limitad...,Campo Grande,Analista De Desenvolvimento De Sistemas,2124,Analistas de tecnologia da informação,212,Profissionais Da Informática,"Com. e administraçao de imóveis, valores mobil...",zero/não declarado

Warning: Total number of columns (31) exceeds max_columns (20) limiting to first (20) columns.
Warning: total number of rows (2134036) exceeds max_rows (20000). Limiting to first (20000) rows.
Warning: Total number of columns (31) exceeds max_columns (20) limiting to first (20) columns.
Warning: total number of rows (2134036) exceeds max_rows (20000). Limiting to first (20000) rows.

In [ ]:
df_tempo_trabalho = pd.read_csv('/content/drive/MyDrive/RESIDÊNCIA /Imersão /data/df_tempo_trabalho.csv')

print("--- df tempocarregado: ---")
display(df_tempo_trabalho.head())

--- df tempocarregado: ---

,Unnamed: 0,ano,sigla_uf,tipo_vinculo,tempo_emprego,mes_admissao,mes_desligamento,vinculo_ativo_3112,vinculo_ativo_3112_valor,subsetor_ibge_valor,descricao,valor_remuneracao_media,faixa_salarial
0,0,2019,CE,10,9.9,NaN,7.0,0,não,Comércio atacadista,Analista De Suporte Computacional,1272.33,"0,51 a 1,00 salários mínimos"
1,1,2019,CE,10,9.9,NaN,7.0,0,não,Comércio atacadista,Analista De Suporte Computacional,1272.33,"0,51 a 1,00 salários mínimos"
2,2,2019,RS,10,7.9,5.0,NaN,1,sim,Comércio varejista,Técnico De Suporte Ao Usuário De Tecnologia Da...,1344.47,"0,51 a 1,00 salários mínimos"
3,3,2019,RS,10,7.9,5.0,NaN,1,sim,Comércio varejista,Técnico De Suporte Ao Usuário De Tecnologia Da...,1344.47,"0,51 a 1,00 salários mínimos"
4,4,2019,RS,10,7.8,5.0,NaN,1,sim,"Ind. da borracha, fumo, couros, peles, similar...",Analista De Suporte Computacional,2624.93,"1,51 a 2,00 salários mínimos"

In [ ]:
df_analise_tempo = df_tempo_trabalho[df_tempo_trabalho['ano'] >= 2022].copy()

# CRIANDO UMA FLAG PARA SUBSTITUIR O NAN POR 0
colunas_evento = ['mes_admissao', 'mes_desligamento']
df_analise_tempo[colunas_evento] = df_analise_tempo[colunas_evento].fillna(0)

df_analise_tempo['admissao_flag'] = (df_analise_tempo['mes_admissao'] > 0).astype(int)


df_analise_tempo['desligamento_flag'] = (df_analise_tempo['mes_desligamento'] > 0).astype(int)

print("sucesso")

sucesso

In [ ]:
# Agrupa por ano, setor e função (descrição)
# E então somamos as flags (1s e 0s) para contar os eventos
df_demanda_tempo = df_analise_tempo.groupby(
    ['ano', 'subsetor_ibge_valor', 'descricao']
).agg(
    total_Admissoes=('admissao_flag', 'sum'),
    total_Desligamentos=('desligamento_flag', 'sum'),
    total_Ativos_Fim_Ano=('vinculo_ativo_3112', 'sum')
).reset_index()

In [ ]:

# Esta é a métrica de "demanda líquida"
df_demanda_tempo['saldo_vagas'] = df_demanda_tempo['total_Admissoes'] - df_demanda_tempo['total_Desligamentos']

# --- 5. Análise dos Resultados ---

# Ordena para ver os maiores saldos (maior demanda) por ano
df_demanda_tempo_ordenada = df_demanda_tempo.sort_values(
    by=['ano', 'saldo_vagas'],
    ascending=[False, False] # Ano mais recente, maior saldo
)

# Exibe os principais resultados
print("\n--- Top 10 Setores/Funções por saldo de Vagas ---")
display(df_demanda_tempo_ordenada.head(10))

--- Top 10 Setores/Funções por saldo de Vagas ---

,ano,subsetor_ibge_valor,descricao,total_Admissoes,total_Desligamentos,total_Ativos_Fim_Ano,saldo_vagas
912,2024,"Com. e administraçao de imóveis, valores mobil...",Analista De Desenvolvimento De Sistemas,23790,21700,69076,2090
926,2024,"Com. e administraçao de imóveis, valores mobil...",Técnico De Suporte Ao Usuário De Tecnologia Da...,9254,7378,18226,1876
919,2024,"Com. e administraçao de imóveis, valores mobil...",Desenvolvedor De Sistemas De Tecnologia Da Inf...,10228,8930,23998,1298
915,2024,"Com. e administraçao de imóveis, valores mobil...",Analista De Suporte Computacional,10516,9708,27144,808
1225,2024,"Instituiçoes de crédito, seguros e capitalizaçao",Analista De Desenvolvimento De Sistemas,5316,4584,14658,732
913,2024,"Com. e administraçao de imóveis, valores mobil...",Analista De Redes E De Comunicação De Dados,3712,3308,8238,404
921,2024,"Com. e administraçao de imóveis, valores mobil...",Engenheiro De Aplicativos Em Computação,1158,870,3148,288
911,2024,"Com. e administraçao de imóveis, valores mobil...",Administrador Em Segurança Da Informação,1366,1080,3458,286
1312,2024,Transportes e comunicaçoes,Técnico De Suporte Ao Usuário De Tecnologia Da...,1604,1320,3000,284
916,2024,"Com. e administraçao de imóveis, valores mobil...",Analista De Testes De Tecnologia Da Informação,1530,1276,4816,254

In [ ]:
from google.colab import files

file_demanda_vagas = 'df_demanda_vagas_ti.xlsx'


df_demanda_tempo_ordenada.to_excel(file_demanda_vagas, merge_cells=False, index=False)

print(f"Os arquivos '{file_demanda_vagas}' foram criados e estão prontos para download.")

files.download(file_demanda_vagas)

Os arquivos 'df_demanda_vagas_ti.xlsx' foram criados e estão prontos para download.